---
blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/jheddings/spectrik/discussions
    about: >-
      Have a question or want to discuss something?
      Start a discussion instead!
